---
# Build and release WASM
# Only triggered on tags
name: Build and Release WASM
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fast"

jobs:
  build:
    name: Build WASM
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential
          rustup default stable
          rustup target add wasm32-unknown-unknown
          cargo install ic-wasm candid-extractor

      - name: Build
        run: |
          bash ./scripts/build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: wasm

  deploy:
    name: Release WASM
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-build
          path: .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: wasm/*
